replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  metrics:  
    - name: cpu
      averageUtilization: 70

components:
  back:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      metrics:
        - name: cpu
          averageUtilization: 50

  service:
    enabled: true
    autoscaling: 
      enabled: true
      minReplicas: 2
      maxReplicas: 4
      metrics:
        - name: memory
          averageUtilization: 75

  front:
    enabled: true
    autoscaling:
      enabled: true
