replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

Release:
  name: 123
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  list:   
    back:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50
    service:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetRAMUtilizationPercentage: 75
