{{- range $name, $cfg := .Values.components }}
{{- if $cfg.enabled }}
{{- $defaultAutoscaling := $.Values.autoscaling }}
{{- $componentAutoscaling := default dict $cfg.autoscaling }}

{{- $enabled := default $defaultAutoscaling.enabled $componentAutoscaling.enabled }}
{{- if $enabled }}
{{- $minReplicas := default $defaultAutoscaling.minReplicas $componentAutoscaling.minReplicas }}
{{- $maxReplicas := default $defaultAutoscaling.maxReplicas $componentAutoscaling.maxReplicas }}
{{- $metrics := default $defaultAutoscaling.metrics $componentAutoscaling.metrics }}

{{- if and $enabled $metrics}}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "demo-hpa.fullname" $ }}-{{ $name }}
    labels:
        {{- include "demo-hpa.labels" $ | nindent 8 }}
        app.kubernetes.io/components: {{ $name }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "demo-hpa.fullname" $ }}-{{ $name }}

    minReplicas: {{ $minReplicas }}
    maxReplicas: {{ $maxReplicas }}

    metrics:
      {{- range $metric := $metrics }}
      - type: Resource
        resource:
          name: {{ $metric.name }}
          target:
            type: Utilization
            averageUtilization: {{ $metric.averageUtilization }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}