apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "demo-hpa.fullname" . }}
    labels:
        {{- include "demo-hpa.labels" . | nindent 4 }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "demo-hpa.fullname" . }}

    minReplicas: {{ .Values.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.autoscaling.maxReplicas }}

    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}

